### ISSUE TITLE
Release prep branch

### ISSUE THREAD

**Issue by chrzyki** [tupuni/polynesianoutliersvoyaging#11]
@tupuni you can find commits for the release preparations in this branch: https://github.com/tupuni/polynesianoutliersvoyaging/tree/release-prep

**Comment by tupuni** [comment]
@chrzyki I have made my changes on my current branch. I am still ignorant about how Pull requests works and how to push on another branch

**Comment by tupuni** [comment]
sorry I'm just afraid to make a wrong move

**Comment by chrzyki** [comment]
No worries and no such thing as a wrong move in Git; everything can be restored/rebuilt. :) I'll merge the PR.

**Comment by chrzyki** [comment]
Done (please check `git log`/https://github.com/tupuni/polynesianoutliersvoyaging/commits/main). I have included all your patches/fixes. I'll have another round through all the figures in a bit.

**Comment by chrzyki** [comment]
(btw: Since `.DS_Store` and `.Rhistory` have been part of the repository before, they come creeping back in with your commits and the rules in `.gitignore` are being, well, ignored: You can either not add them to a commit or remove them locally with something like `git rm --cached .DS_Store`)

**Comment by chrzyki** [comment]
Should we plan one final Zoom session together to go through all the changes and wrap everything up?

**Comment by tupuni** [comment]
Hi @chrzyki yes absolutely, I'm available today and tomorrow in the evening (in the morning of your next monday and tuesday, 28 and 29th of November). Around 8 would be good for me.
