### ISSUE TITLE
Include reference to the release versions of the data sets that have been used

### ISSUE THREAD

**Issue by chrzyki** [tupuni/polynesianoutliersvoyaging#13]
I.e. for Pofatu link directly to Zenodo in the README:

- [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4726799.svg)](https://doi.org/10.5281/zenodo.4726799)

Likewise for GEOROC:

- [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.6782177.svg)](https://doi.org/10.5281/zenodo.6782177)

**Comment by tupuni** [comment]
I included these in https://github.com/tupuni/polynesianoutliersvoyaging/blob/main/README.md
