### ISSUE TITLE
binder links & Co.

### ISSUE THREAD

**Issue by chrzyki** [tupuni/polynesianoutliersvoyaging#14]
Since the analysis requires manual intervention in terms of researchers having to manually download the two database files, the automatically included links to binder and the like will never work. If that's something you'd like to have for your audience we either
- a) have to include an automatic way of downloading the artifacts from Zenodo, unzipping the relevant parts or
- b) have to provide the two databases as artifacts for binder & Co.

Do you have any thoughts/preferences?

**Comment by tupuni** [comment]
Providing a straightforward way to automatically download the two databases would be great, for this paper and for Pofatu users in general. The georoc sqlite database comes as a compressed .gz file that needs unzipping, I guess that should also be automatized.

**Comment by chrzyki** [comment]
Remove the binder link for now and provide later if needed.

**Comment by chrzyki** [comment]
Removed for now in 920b6feae57946685583a3c0528f00c3a038b667.
