### ISSUE TITLE
R >= 4.0 is required for dependencies

### ISSUE THREAD

**Issue by chrzyki** [tupuni/polynesianoutliersvoyaging#6]
< 4.0 should be possible but requires manual intervention with respect to certain dependencies.

**Comment by tupuni** [comment]
Yes I realized that recently. What's your suggestion? Shall I add that to the Readme?

**Comment by chrzyki** [comment]
Closed in 78d33a3b8606ffce7433f2fb7cf2679a94cbdf0f.
